cmake_minimum_required(VERSION 2.4)
project(scutclient C)
ADD_DEFINITIONS(-Os -Wall)
find_package(CURL REQUIRED)
include_directories(${CURL_INCLUDE_DIRS})
add_executable(scutclient src/auth.c src/drcom.c src/functions.c src/info.c src/main.c src/md5.c src/portal.c src/runtime_status.c src/tracelog.c)
target_link_libraries(scutclient ${CURL_LIBRARIES})
install(TARGETS scutclient RUNTIME DESTINATION bin)
